Feature/id 06/expense crud operations
programacion-6/ExpenseTrackerGrupo4 pull request #10
Opened 2024-09-25 06:52 UTC by fabian-romero-jalafund

2024-09-25 17:46 UTC, luis-espinoza-jalafund requested changes

2024-09-25 17:46 UTC, luis-espinoza-jalafund commented on src/Infrastructure/Interfaces/IRepository.cs
> +}
MIssing endline

2024-09-25 17:46 UTC, luis-espinoza-jalafund commented on src/Presentation/Controllers/ExpenseController.cs
> +        return Ok(expenses);
When a range of a day is set to itself, the answer is empty even if there is data for that date.
![image](https://github.com/user-attachments/assets/31fc53a3-456e-42b9-82fb-3348d7052f30)
![image](https://github.com/user-attachments/assets/d4014fe7-0774-4927-ad61-446230b5a941)

2024-09-25 17:46 UTC, luis-espinoza-jalafund commented on src/Presentation/Controllers/ExpenseController.cs
> +            return NoContent();
An ok could be returned instead of a NoContent to avoid having a 204 response that is undocumented or document the 204 response.

2024-09-25 17:46 UTC, luis-espinoza-jalafund commented on src/Presentation/Controllers/ExpenseController.cs
> +            return Forbid();
Despite being logged in and being able to use the other endpoints I get no response from this one.
![image](https://github.com/user-attachments/assets/06f31ca7-8bfd-487f-81b9-f162c3e2a328)

2024-09-26 05:30 UTC, leonardo-herrera-jalafund requested changes

2024-09-26 05:30 UTC, leonardo-herrera-jalafund commented on src/Presentation/Controllers/ExpenseController.cs
> +    [Authorize]
No es necesario declarar [Authorize] en cada metodo si ya lo declaraste en la clase.

2024-09-26 05:30 UTC, leonardo-herrera-jalafund commented on src/Presentation/Controllers/ExpenseController.cs
> +    [Authorize]
No es necesario declarar [Authorize] en cada metodo si ya lo declaraste en la clase.

2024-09-26 05:30 UTC, leonardo-herrera-jalafund commented on src/Presentation/Controllers/ExpenseController.cs
> +    [Authorize]
No es necesario declarar [Authorize] en cada metodo si ya lo declaraste en la clase.

2024-09-26 05:30 UTC, leonardo-herrera-jalafund commented on src/Presentation/Controllers/ExpenseController.cs
> +    [Authorize]
No es necesario declarar [Authorize] en cada metodo si ya lo declaraste en la clase.

2024-09-26 05:30 UTC, leonardo-herrera-jalafund commented on src/Presentation/Controllers/ExpenseController.cs
> +    [Authorize]
No es necesario declarar [Authorize] en cada metodo si ya lo declaraste en la clase.

2024-09-26 05:30 UTC, leonardo-herrera-jalafund commented on src/Presentation/Controllers/ExpenseController.cs
> +        catch (UnauthorizedAccessException)
El bloque try-catch nunca capturará la excepción ya que si el usuario no está autorizado el metodo no se ejecutará.

2024-09-26 05:30 UTC, leonardo-herrera-jalafund commented on src/Presentation/Controllers/ExpenseController.cs
> +        catch (UnauthorizedAccessException)
El bloque try-catch nunca capturará la excepción ya que si el usuario no está autorizado el método no se ejecutará.

2024-09-26 05:30 UTC, leonardo-herrera-jalafund commented on src/Presentation/Controllers/ExpenseController.cs
> +        catch (UnauthorizedAccessException)
El bloque try-catch nunca capturará la excepción ya que si el usuario no está autorizado el metodo no se ejecutará.

2024-09-26 06:10 UTC, luis-espinoza-jalafund approved these changes

2024-09-26 06:11 UTC, merged