Feature/id 02/user management
programacion-6/ExpenseTrackerGrupo4 pull request #9
Opened 2024-09-25 06:36 UTC by leonardo-herrera-jalafund

User management:
User service & User controller implemented

2024-09-25 14:07 UTC, luis-espinoza-jalafund requested changes

2024-09-25 14:07 UTC, luis-espinoza-jalafund commented on src/Presentation/Controllers/UserController.cs
> +}
Missing endline

2024-09-25 14:07 UTC, luis-espinoza-jalafund commented on src/Presentation/Controllers/UserController.cs
> +        return Ok();
The return should be user and not only "ok" assuming we have an admin view.

2024-09-25 14:07 UTC, luis-espinoza-jalafund commented on src/Presentation/Controllers/UserController.cs
> +    [HttpGet("{id}")]
missing authorization

2024-09-25 14:07 UTC, luis-espinoza-jalafund commented on src/Presentation/Controllers/UserController.cs
> +    [HttpPut]
Missing authorization

2024-09-25 14:07 UTC, luis-espinoza-jalafund commented on src/Presentation/Controllers/UserController.cs
> +        return Ok();
The return should be user and not only "ok" assuming we have an admin view.

2024-09-25 14:07 UTC, luis-espinoza-jalafund commented on src/Presentation/Controllers/UserController.cs
> +    [HttpGet("email/{email}")]
Missing athorization

2024-09-25 14:07 UTC, luis-espinoza-jalafund commented on src/Presentation/Controllers/UserController.cs
> +        return Ok();
When updating the data, the password is not hashed again.
![image](https://github.com/user-attachments/assets/23ef5a38-757a-4d9b-8b0f-245d254a8e80)

2024-09-25 14:07 UTC, luis-espinoza-jalafund commented on src/Presentation/Controllers/UserController.cs
> +    [HttpDelete("{id}")]
missing authorization

2024-09-25 18:10 UTC, 0santisimo0 reviewed
Implement IRepository to IUserRepository

2024-09-25 18:10 UTC, 0santisimo0 requested changes
Implement IRepository to IUserRepository

2024-09-25 18:12 UTC, santiago-caballero-jalafund requested changes
Implement IRepository to IUserRepository

2024-09-26 15:32 UTC, santiago-caballero-jalafund requested changes
Use a DTO for User to not expose the id

2024-09-27 02:11 UTC, 0santisimo0 approved these changes

2024-09-27 17:40 UTC, luis-espinoza-jalafund requested changes

2024-09-27 17:40 UTC, luis-espinoza-jalafund commented on src/Presentation/Controllers/UserController.cs
> +    public async Task<IActionResult> UpdateUser([FromBody] UserUpdateRequestDTO userUpdated)
The id should not be requested in the body, it should be a field like getById or Delete

2024-09-27 17:40 UTC, luis-espinoza-jalafund commented on src/Presentation/DTOs/UserUpdateRequestDTO.cs
> +}
Missing endline

2024-09-27 17:40 UTC, luis-espinoza-jalafund commented on src/Presentation/Profiles/UserProfile.cs
> +}
Missing endline

2024-09-28 03:44 UTC, santiago-caballero-jalafund approved these changes

2024-09-30 12:27 UTC, luis-espinoza-jalafund approved these changes

2024-09-30 12:28 UTC, merged